<template>
  <b-navbar
    variant="primary"
    toggleable="lg"
    type="dark"
    fixed="top"
  >
    <b-navbar-brand to="/" class="d-flex align-items-center">
      <b-img
        src="/g5-logo.png"
        width="40"
        height="40"
        alt="g5-logo"
        title="G5 Marketing"
        class="mx-3"
      />
      <h1 class="h1-nav-brand">
        Operational Excellence
        <octopus :size="`0.75em`" :color="`#7898ad`" class="jello-vertical" />
      </h1>
    </b-navbar-brand>
    <!-- Right aligned nav items -->
    <b-navbar-nav class="ml-auto pr-2">
      <slot name="content" />
    </b-navbar-nav>
  </b-navbar>
</template>

<script>
import Octopus from '~/components/icons/octopus'
export default {
  components: {
    Octopus
  },
  data() {
    return {}
  }
}
</script>

<style>
.h1-nav-brand {
  font-size: 1.5em;
  margin-bottom: 0;
}
.jello-vertical {
  transform: scale3d(1, 1, 1);
  transform-style: preserve-3d;
  transition: 300ms ease-in-out;
}
.h1-nav-brand:hover .jello-vertical {
  animation: jello-vertical 0.9s ease-in-out 300ms both infinite;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-2-5 9:9:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */
/**
 * ----------------------------------------
 * animation jello-vertical
 * ----------------------------------------
 */
@keyframes jello-vertical {
  0% {
    transform: scale3d(1, 1, 1);
  }
  30% {
    transform: scale3d(0.75, 1.25, 1);
  }
  40% {
    transform: scale3d(1.25, 0.75, 1);
  }
  50% {
    transform: scale3d(0.85, 1.15, 1);
  }
  65% {
    transform: scale3d(1.05, 0.95, 1);
  }
  75% {
    transform: scale3d(0.95, 1.05, 1);
  }
  100% {
    transform: scale3d(1, 1, 1);
  }
}
</style>
